apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: herik-frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      apptype: frontend
      env: prod
      